// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
    [Migration("20250428092945_miInitial")]
========
    [Migration("20250428093148_miInitial")]
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
    partial class miInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.ActivityDbM", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityLevelDbMActivityLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrDate")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrDayOfWeek")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityLevelDbMActivityLevelId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("Activities", "supusr");
                });

            modelBuilder.Entity("DbModels.ActivityLevelDbM", b =>
                {
                    b.Property<Guid>("ActivityLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ActivityLevelId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("ActivityLevels", "supusr");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("b81bc185-51bc-45f5-bf47-5b05999cd651"),
========
                            ActivityLevelId = new Guid("231b8e17-f4e0-4833-8b20-8323335013b8"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Resting 🛌",
                            Name = "Resting",
                            Rating = 1
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("a86acc89-c30e-40a4-bda1-b9524f7bcedb"),
========
                            ActivityLevelId = new Guid("c41e433a-4274-4308-8414-59aeb9848f19"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Reading 📖",
                            Name = "Reading",
                            Rating = 3
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("c2c435d1-1708-4f2f-8498-162cf64440e7"),
========
                            ActivityLevelId = new Guid("5e2166da-ad93-4cd9-93fd-213c9f3291ea"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Take a Walk 🚶‍♂️",
                            Name = "Take a Walk",
                            Rating = 5
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("71efd8e0-f61f-4b83-a1f9-ce859ac7499a"),
========
                            ActivityLevelId = new Guid("559f45aa-af52-4d47-9401-915040ec5849"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Jogging 🏃‍♂️",
                            Name = "Jogging",
                            Rating = 10
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("a97a2ab9-9e40-453b-8240-3835d3aaf441"),
========
                            ActivityLevelId = new Guid("b7ee4e1e-3551-4a24-8aa4-529219ee9cd2"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Swimming 🏊‍♂️",
                            Name = "Swimming",
                            Rating = 7
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            ActivityLevelId = new Guid("9e01cf41-93db-4edd-a9e0-e94068e8e421"),
========
                            ActivityLevelId = new Guid("5783350d-19f5-430b-8403-d8041e03d541"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Training 🏋️‍♂️",
                            Name = "Training",
                            Rating = 9
                        });
                });

            modelBuilder.Entity("DbModels.AppetiteDbM", b =>
                {
                    b.Property<Guid>("AppetiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppetiteLevelDbMAppetiteLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrDate")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrDayOfWeek")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppetiteId");

                    b.HasIndex("AppetiteLevelDbMAppetiteLevelId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("Appetites", "supusr");
                });

            modelBuilder.Entity("DbModels.AppetiteLevelDbM", b =>
                {
                    b.Property<Guid>("AppetiteLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("AppetiteLevelId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("AppetiteLevels", "supusr");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            AppetiteLevelId = new Guid("3a43f47a-7b71-481a-84c4-c8cb4c988679"),
========
                            AppetiteLevelId = new Guid("63b6618c-38dd-4577-842a-fcad1aefd4d8"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Didn't Eat At All 🤢",
                            Name = "Didn't Eat At All",
                            Rating = 1
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            AppetiteLevelId = new Guid("e0fac1fa-6f65-4e7a-b85e-5345890ca321"),
========
                            AppetiteLevelId = new Guid("8640dbc5-765e-41f7-a160-cfd0e6c8e3a9"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Little 🍽️",
                            Name = "Little",
                            Rating = 3
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            AppetiteLevelId = new Guid("4b3d9e53-55dc-43a9-8ecb-c78d933a5cc6"),
========
                            AppetiteLevelId = new Guid("dcffb13d-1bd6-4002-a411-99101de68952"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Normal Appetite 🙂",
                            Name = "Normal",
                            Rating = 5
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            AppetiteLevelId = new Guid("960ac13a-e84d-4275-98d7-bf84a310721b"),
========
                            AppetiteLevelId = new Guid("0e349508-81dc-4b6d-bbe6-d605e4711abd"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Medium 😋",
                            Name = "Medium",
                            Rating = 7
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            AppetiteLevelId = new Guid("2d91da61-5792-407c-8685-0f1e048663fa"),
========
                            AppetiteLevelId = new Guid("7412f31e-1a60-437a-92f6-a88eed546747"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Very Much 🍴",
                            Name = "Very Much",
                            Rating = 10
                        });
                });

            modelBuilder.Entity("DbModels.GraphDbM", b =>
                {
                    b.Property<Guid>("GraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GraphId");

                    b.ToTable("Graphs", "supusr");
                });

            modelBuilder.Entity("DbModels.MoodDbM", b =>
                {
                    b.Property<Guid>("MoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<Guid?>("MoodKindDbMMoodKindId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrDate")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrDayOfWeek")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MoodId");

                    b.HasIndex("MoodKindDbMMoodKindId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("Moods", "supusr");
                });

            modelBuilder.Entity("DbModels.MoodKindDbM", b =>
                {
                    b.Property<Guid>("MoodKindId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("MoodKindId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("MoodKinds", "supusr");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("3e6d933a-7cf5-4a39-bef4-d376395f9c7a"),
========
                            MoodKindId = new Guid("b76b1741-4fb5-40a8-af38-d71c158e37ea"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Happy 😃",
                            Name = "Happy",
                            Rating = 10
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("0ef428d4-f741-459a-9a10-be02b1bf9cd8"),
========
                            MoodKindId = new Guid("a6f07910-961c-4a46-8380-eb43d4edb0b8"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Sad 🙁",
                            Name = "Sad",
                            Rating = 2
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("64ed15dd-21e7-4987-845a-fb5831ddd392"),
========
                            MoodKindId = new Guid("3c6b3571-945d-41ad-81ca-8d90a2699cd3"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Angry 😡",
                            Name = "Angry",
                            Rating = 3
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("4b42e1a4-9496-423f-b7bd-a26e29dfab49"),
========
                            MoodKindId = new Guid("cf3132ab-d808-4fea-8ee1-1700d0fc4e02"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Lovely 😍",
                            Name = "Lovely",
                            Rating = 7
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("090f2d39-fc71-491e-a006-42ca47e9d7d8"),
========
                            MoodKindId = new Guid("20449aa4-ea55-47d2-9559-a7ba90606b63"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Depressed 😢",
                            Name = "Depressed",
                            Rating = 1
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("a69bf5ef-ebcf-4ecd-812f-2e3fa339ffc1"),
========
                            MoodKindId = new Guid("e2cfe8be-8859-49d2-832d-cc4fe8e2781a"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Excited 🤩",
                            Name = "Excited",
                            Rating = 9
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            MoodKindId = new Guid("fe9bfdb1-f5f6-4ece-bcc3-899b976ec52b"),
========
                            MoodKindId = new Guid("5468ce36-b660-4cd4-a757-5ac2123fa81d"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Bored 😒",
                            Name = "Bored",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("DbModels.PatientDbM", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("GraphId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("StaffDbMStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PatientId");

                    b.HasIndex("GraphId")
                        .IsUnique()
                        .HasFilter("[GraphId] IS NOT NULL");

                    b.HasIndex("StaffDbMStaffId");

                    b.ToTable("Patients", "supusr");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("8b54023e-13bb-463a-8d0d-2742b39a3fd1"),
========
                            PatientId = new Guid("1f5d21d8-e9eb-4a7a-93ad-03080d8936a0"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "Madi",
                            LastName = "Alabama",
                            PersonalNumber = "19560831-1111"
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("41b223c5-ce01-4f8b-8fd0-9868bff1bec8"),
========
                            PatientId = new Guid("bc12c446-43d0-45fe-8c47-3fc27fc3c082"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "John",
                            LastName = "Doe",
                            PersonalNumber = "19480516-2222"
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("3cff38a9-bd45-48f5-af5d-f6d84ca9cec1"),
========
                            PatientId = new Guid("2f206bdf-b54b-4799-a3dd-42cf3aac0981"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "Jane",
                            LastName = "Smith",
                            PersonalNumber = "19610228-1212"
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("dfde9665-8ee9-492c-9afe-5b193382dac5"),
========
                            PatientId = new Guid("c7b59ff5-191b-4fcd-8250-e19b7f422fc4"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PersonalNumber = "19450801-4444"
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("7ca661b7-9abd-4471-8a83-9f0aaef31e73"),
========
                            PatientId = new Guid("c90fe0a2-c90d-472a-a126-dc19c6a51251"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "Bob",
                            LastName = "Brown",
                            PersonalNumber = "19501110-1331"
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            PatientId = new Guid("d566d722-0d1a-4913-a544-7d3c3e38269d"),
========
                            PatientId = new Guid("a4239d9b-9e6b-442d-b287-e9c9e5073877"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            FirstName = "Charlie",
                            LastName = "Davis",
                            PersonalNumber = "19511231-16181"
                        });
                });

            modelBuilder.Entity("DbModels.SleepDbM", b =>
                {
                    b.Property<Guid>("SleepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SleepLevelDbMSleepLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrDate")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StrDayOfWeek")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SleepId");

                    b.HasIndex("PatientDbMPatientId");

                    b.HasIndex("SleepLevelDbMSleepLevelId");

                    b.ToTable("Sleeps", "supusr");
                });

            modelBuilder.Entity("DbModels.SleepLevelDbM", b =>
                {
                    b.Property<Guid>("SleepLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PatientDbMPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("SleepLevelId");

                    b.HasIndex("PatientDbMPatientId");

                    b.ToTable("SleepLevels", "supusr");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            SleepLevelId = new Guid("1dd66f87-640f-4ea9-bd19-a4f290e7a9e6"),
========
                            SleepLevelId = new Guid("f4906fe7-3608-491f-91aa-1dc272b0e7f7"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Low Sleep Level 🙁",
                            Name = "Low",
                            Rating = 5
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            SleepLevelId = new Guid("e20e4040-9a0f-4a42-89fd-b2ea668da682"),
========
                            SleepLevelId = new Guid("02faffd2-f1fa-49a6-9312-d205cf2259a6"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Medium Sleep Level 😐",
                            Name = "Medium",
                            Rating = 6
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            SleepLevelId = new Guid("53b01a98-d37b-48a2-921c-51c647c70a61"),
========
                            SleepLevelId = new Guid("80b9b73e-c122-4d0c-9f78-68006277de47"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "OK Sleep Level 🙂",
                            Name = "OK",
                            Rating = 8
                        },
                        new
                        {
<<<<<<<< HEAD:DbContext/Migrations/SqlServerDbContext/20250428092945_miInitial.Designer.cs
                            SleepLevelId = new Guid("84a1df17-eeef-484b-96f3-a4c0e7526d6b"),
========
                            SleepLevelId = new Guid("690e5bba-8fb8-4343-8684-94ad5f16018b"),
>>>>>>>> 33c538c5673b6d7bc6542909128a9c0fc37d9e33:DbContext/Migrations/SqlServerDbContext/20250428093148_miInitial.Designer.cs
                            Label = "Too much Sleep Level 😃",
                            Name = "Too much",
                            Rating = 10
                        });
                });

            modelBuilder.Entity("DbModels.StaffDbM", b =>
                {
                    b.Property<Guid>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs", "supusr");
                });

            modelBuilder.Entity("DbModels.UserDbM", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Models.DTO.GstUsrInfoDbDto", b =>
                {
                    b.Property<int>("NrActivities")
                        .HasColumnType("int");

                    b.Property<int>("NrAppetites")
                        .HasColumnType("int");

                    b.Property<int>("NrGraphs")
                        .HasColumnType("int");

                    b.Property<int>("NrMoods")
                        .HasColumnType("int");

                    b.Property<int>("NrPatients")
                        .HasColumnType("int");

                    b.Property<int>("NrSleeps")
                        .HasColumnType("int");

                    b.Property<int>("NrStaffs")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("vwInfoDb", "gstusr");
                });

            modelBuilder.Entity("Models.DTO.GstUsrInfoStaffsDto", b =>
                {
                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NrPatients")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vwInfoStaffs", "gstusr");
                });

            modelBuilder.Entity("DbModels.ActivityDbM", b =>
                {
                    b.HasOne("DbModels.ActivityLevelDbM", "ActivityLevelDbM")
                        .WithMany("ActivitiesDbM")
                        .HasForeignKey("ActivityLevelDbMActivityLevelId");

                    b.HasOne("DbModels.PatientDbM", "PatientDbM")
                        .WithMany()
                        .HasForeignKey("PatientDbMPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevelDbM");

                    b.Navigation("PatientDbM");
                });

            modelBuilder.Entity("DbModels.ActivityLevelDbM", b =>
                {
                    b.HasOne("DbModels.PatientDbM", null)
                        .WithMany("ActivityLevelsDbM")
                        .HasForeignKey("PatientDbMPatientId");
                });

            modelBuilder.Entity("DbModels.AppetiteDbM", b =>
                {
                    b.HasOne("DbModels.AppetiteLevelDbM", "AppetiteLevelDbM")
                        .WithMany("AppetitesDbM")
                        .HasForeignKey("AppetiteLevelDbMAppetiteLevelId");

                    b.HasOne("DbModels.PatientDbM", "PatientDbM")
                        .WithMany()
                        .HasForeignKey("PatientDbMPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppetiteLevelDbM");

                    b.Navigation("PatientDbM");
                });

            modelBuilder.Entity("DbModels.AppetiteLevelDbM", b =>
                {
                    b.HasOne("DbModels.PatientDbM", null)
                        .WithMany("AppetiteLevelsDbM")
                        .HasForeignKey("PatientDbMPatientId");
                });

            modelBuilder.Entity("DbModels.MoodDbM", b =>
                {
                    b.HasOne("DbModels.MoodKindDbM", "MoodKindDbM")
                        .WithMany("MoodsDbM")
                        .HasForeignKey("MoodKindDbMMoodKindId");

                    b.HasOne("DbModels.PatientDbM", "PatientDbM")
                        .WithMany()
                        .HasForeignKey("PatientDbMPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodKindDbM");

                    b.Navigation("PatientDbM");
                });

            modelBuilder.Entity("DbModels.MoodKindDbM", b =>
                {
                    b.HasOne("DbModels.PatientDbM", null)
                        .WithMany("MoodKindsDbM")
                        .HasForeignKey("PatientDbMPatientId");
                });

            modelBuilder.Entity("DbModels.PatientDbM", b =>
                {
                    b.HasOne("DbModels.GraphDbM", "GraphDbM")
                        .WithOne("PatientDbM")
                        .HasForeignKey("DbModels.PatientDbM", "GraphId");

                    b.HasOne("DbModels.StaffDbM", null)
                        .WithMany("PatientsDbM")
                        .HasForeignKey("StaffDbMStaffId");

                    b.Navigation("GraphDbM");
                });

            modelBuilder.Entity("DbModels.SleepDbM", b =>
                {
                    b.HasOne("DbModels.PatientDbM", "PatientDbM")
                        .WithMany()
                        .HasForeignKey("PatientDbMPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.SleepLevelDbM", "SleepLevelDbM")
                        .WithMany("SleepsDbM")
                        .HasForeignKey("SleepLevelDbMSleepLevelId");

                    b.Navigation("PatientDbM");

                    b.Navigation("SleepLevelDbM");
                });

            modelBuilder.Entity("DbModels.SleepLevelDbM", b =>
                {
                    b.HasOne("DbModels.PatientDbM", null)
                        .WithMany("SleepLevelsDbM")
                        .HasForeignKey("PatientDbMPatientId");
                });

            modelBuilder.Entity("DbModels.ActivityLevelDbM", b =>
                {
                    b.Navigation("ActivitiesDbM");
                });

            modelBuilder.Entity("DbModels.AppetiteLevelDbM", b =>
                {
                    b.Navigation("AppetitesDbM");
                });

            modelBuilder.Entity("DbModels.GraphDbM", b =>
                {
                    b.Navigation("PatientDbM")
                        .IsRequired();
                });

            modelBuilder.Entity("DbModels.MoodKindDbM", b =>
                {
                    b.Navigation("MoodsDbM");
                });

            modelBuilder.Entity("DbModels.PatientDbM", b =>
                {
                    b.Navigation("ActivityLevelsDbM");

                    b.Navigation("AppetiteLevelsDbM");

                    b.Navigation("MoodKindsDbM");

                    b.Navigation("SleepLevelsDbM");
                });

            modelBuilder.Entity("DbModels.SleepLevelDbM", b =>
                {
                    b.Navigation("SleepsDbM");
                });

            modelBuilder.Entity("DbModels.StaffDbM", b =>
                {
                    b.Navigation("PatientsDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
